import Menu from "../componentes/menu"
import "./css/base.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
       <Menu/>
       </header>
         <main>
         {children}
         </main>
        
      <footer>
        <p>LPI 27/11/25</p>
      </footer>
      </body>
    </html>
  )
}
